version: 2.1
orbs:
  cypress: cypress-io/cypress@1

jobs:
  build:
    docker:
      - image: cimg/node:15.11.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-1-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-1-{{ checksum "package-lock.json" }}
      - persist_to_workspace:
          root: "."
          paths:
            - node_modules
  
  jest_test:
    docker:
      - image: cimg/node:15.11.0
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: "."
      - run: npm run test
      - store_test_results:
          path: ./reports/junit
      - store_artifacts:
          path: ./reports/junit
      - run:
          name: Notify Test Results
          command: node ./scripts/parseJunit.js
          when: always

workflows:
  build_and_test:
    jobs:
      - build
      - jest_test:
          requires:
            - build
      - cypress/run:
          name: Cypress Tests
          start: npm start
          spec: cypress/integration/index.test.js
          post-steps:
            - store_test_results:
                path: ./reports/junit
            - store_artifacts:
                path: cypress/videos
            - store_artifacts:
                path: cypress/screenshots
            - run:
                name: Notify Test Results
                command: node ./scripts/parseJunit.js
                when: always
